### ISSUE TITLE
Express-pouchdb conflicts with app session handling

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/express-pouchdb#122]
@commandoline gave me a simple test on IRC, run this and visit http://127.0.0.1:3000/db

```
var express = require('express')
var session = require('express-session')

var app = express()

app.use(session({secret: 'keyboard cat'}))

app.use("/db", require('express-pouchdb')(require('pouchdb')));

app.get("/", function (req, res) {
  if (req.session.a) {
    req.session.a += 1;
    res.send(req.session.a + "th time!");
  } else {
    req.session.a = 1;
    res.send("first time!");
  }
});

app.listen(3000);
```

It dies with either 

```
/Users/daleharvey/src/janus/node_modules/express-session/index.js:268
      req.session.touch();
                  ^
TypeError: Object #<Object> has no method 'touch'
    at ServerResponse.end (/Users/daleharvey/src/janus/node_modules/express-session/index.js:268:19)
    at ServerResponse.res.end (/Users/daleharvey/src/janus/node_modules/express-pouchdb/node_modules/compression/index.js:117:15)
    at IncomingMessage.write (/Users/daleharvey/src/janus/node_modules/express/node_modules/finalhandler/index.js:118:9)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
```

or 

``` 
/Users/daleharvey/src/janus/node_modules/express-session/index.js:178
      if (cookie.secure && !issecure(req, trustProxy)) {
                ^
TypeError: Cannot read property 'secure' of undefined
    at ServerResponse.<anonymous> (/Users/daleharvey/src/janus/node_modules/express-session/index.js:178:17)
    at ServerResponse.writeHead (/Users/daleharvey/src/janus/node_modules/express-session/node_modules/on-headers/index.js:44:16)
    at ServerResponse.writeHead (/Users/daleharvey/src/janus/node_modules/express-pouchdb/node_modules/compression/node_modules/on-headers/index.js:53:19)
    at ServerResponse._implicitHeader (http.js:1131:8)
    at ServerResponse.res.write (/Users/daleharvey/src/janus/node_modules/express-pouchdb/node_modules/compression/index.js:91:14)
    at ServerResponse.res.end (/Users/daleharvey/src/janus/node_modules/express-pouchdb/node_modules/compression/index.js:112:14)
    at IncomingMessage.write (/Users/daleharvey/src/janus/node_modules/express/node_modules/finalhandler/index.js:118:9)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
```

**Comment by marten-de-vries** [comment]
Fixed: 3920710
