### ISSUE TITLE
Invalid JSON body makes server crash

### ISSUE THREAD

**Issue by marten-de-vries** [pouchdb/express-pouchdb#159]
Reported by @Rybadour:
'Agreed, when the body is JSON and it's not perfect the whole server goes down with an error like this:

```
/home/ryan/projects/websweet/api/node_modules/express-pouchdb/lib/utils.js:53
var rawPath = req.originalUrl.slice(req.baseUrl.length);
^
TypeError: Cannot read property 'length' of undefined
at Object.exports.rawPath (/home/ryan/projects/websweet/api/node_modules/express-pouchdb/lib/utils.js:53:50)
at Array.1 (/home/ryan/projects/websweet/api/node_modules/express-pouchdb/lib/routes/http_log.js:21:31)
at listener (/home/ryan/projects/websweet/api/node_modules/morgan/node_modules/on-finished/index.js:164:15)
at onFinish (/home/ryan/projects/websweet/api/node_modules/morgan/node_modules/on-finished/index.js:95:5)
at callback (/home/ryan/projects/websweet/api/node_modules/morgan/node_modules/on-finished/node_modules/ee-first/index.js:33:10)
at ServerResponse.onevent (/home/ryan/projects/websweet/api/node_modules/morgan/node_modules/on-finished/node_modules/ee-first/index.js:66:5)
at ServerResponse.EventEmitter.emit (events.js:117:20)
at ServerResponse.OutgoingMessage._finish (http.js:1018:8)
at ServerResponse.OutgoingMessage.end (http.js:1001:10)
at ServerResponse.res.end (/home/ryan/projects/websweet/api/node_modules/express-pouchdb/node_modules/compression/index.js:115:15)
```

That's kinda unacceptable.'

**Comment by marten-de-vries** [comment]
Fixed: fc5e5c87c8f4c5d369036bc7da21f8f0d491709e

Thanks for reporting and all the info, @Rybadour!
