### ISSUE TITLE
Weird behavior when setting options

### ISSUE THREAD

**Issue by gelnior** [pouchdb/express-pouchdb#188]
Hello there,

  I'm trying to build an offline first app based on PouchDB. When I write my client side, everything is fine. 
But on server side, things go wrong. What I try to do is to setup on the server side a PouchDB API that allows syncing between browsers. Here is how I setup Express-Pouch:

```coffeescript
db = new PouchDB 'db'
expressPouchDB = require 'express-pouchdb'
app.use '/db', expressPouchDB(db, mode: 'minimumForPouchDB')
 ```

But when I try to access to the API it says it cannot access to the database object. Are you sure of this code? https://github.com/pouchdb/express-pouchdb/blob/master/lib/index.js#L71-L75 
If yes, could you tell me what I do wrong?

Node version: 0.10.26
Express version: 0.4.4

Here is the stacktrace:

```
GET /db 500 1.816 ms - 3512
Error: express-pouchdb needs a PouchDB object to route a request!
  at Layer.handle (.../node_modules/express-pouchdb/lib/index.js:174:13)
  at trim_prefix (.../node_modules/express/lib/router/index.js:255:15)
  at .../node_modules/express/lib/router/index.js:216:9
  at Function.proto.process_params (.../node_modules/express/lib/router/index.js:284:12)
  at next (.../node_modules/express/lib/router/index.js:207:19)
  at Layer.expressInit [as handle] (.../hari/node_modules/express/lib/middleware/init.js:23:5)
....
```

**Comment by gelnior** [comment]
Ok my bad, it doesn't expect the db instance but the PouchDB object. Sorry for the noise.
