### ISSUE TITLE
Error messages in Travis logs

### ISSUE THREAD

**Issue by marten-de-vries** [pouchdb/express-pouchdb#194]
At least:
```
Possibly unhandled Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
    at Object.exports.sendJSON (/home/travis/build/pouchdb/express-pouchdb/lib/utils.js:185:9)
    at Object.exports.sendError (/home/travis/build/pouchdb/express-pouchdb/lib/utils.js:177:11)
    at /home/travis/build/pouchdb/express-pouchdb/lib/routes/compact.js:15:20
    at tryCatch1 (/home/travis/build/pouchdb/express-pouchdb/node_modules/pouchdb/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/home/travis/build/pouchdb/express-pouchdb/node_modules/pouchdb/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/travis/build/pouchdb/express-pouchdb/node_modules/pouchdb/node_modules/bluebird/js/main/promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/travis/build/pouchdb/express-pouchdb/node_modules/pouchdb/node_modules/bluebird/js/main/promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (/home/travis/build/pouchdb/express-pouchdb/node_modules/pouchdb/node_modules/bluebird/js/main/promise.js:1006:14)
    at Promise$_rejectPromises [as _rejectPromises] (/home/travis/build/pouchdb/express-pouchdb/node_modules/pouchdb/node_modules/bluebird/js/main/promise.js:999:10)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/travis/build/pouchdb/express-pouchdb/node_modules/pouchdb/node_modules/bluebird/js/main/async.js:74:12)

Possibly unhandled Error: once called  more than once
    at /home/travis/build/pouchdb/express-pouchdb/node_modules/pouchdb/lib/utils.js:464:13
    at /home/travis/build/pouchdb/express-pouchdb/node_modules/pouchdb/node_modules/argsarray/index.js:14:18
    at tryCatch1 (/home/travis/build/pouchdb/express-pouchdb/node_modules/pouchdb/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/home/travis/build/pouchdb/express-pouchdb/node_modules/pouchdb/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/travis/build/pouchdb/express-pouchdb/node_modules/pouchdb/node_modules/bluebird/js/main/promise.js:711:18)
```
They don't stop the tests from passing but should be investigated.

**Comment by marten-de-vries** [comment]
So a stable way of reproducing problems is using one of the following:
- ``GREP=2913 SERVER=pouchdb-express-router npm test``
- ``GREP=2913 npm run test-pouchdb-minimum``

2913 gives a total of three different errors: once called  more than once, Can't set headers after they are sent. (which seems to be a superficial error only occurring because the others occur) & last but not least:
```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at PouchDB.EventEmitter.addListener (events.js:160:15)
    at PouchDB.EventEmitter.once (events.js:185:8)
    at new Changes (/home/marten/git/pouchdb/lib/changes.js:41:6)
    at PouchDB.AbstractPouchDB.changes (/home/marten/git/pouchdb/lib/adapter.js:689:10)
    at PouchDB.AbstractPouchDB._compact (/home/marten/git/pouchdb/lib/adapter.js:459:8)
...
```

**Comment by nolanlawson** [comment]
It looks like the error might be in PouchDB itself. Following the stacktrace, I'd guess it's somewhere in `adapter.compact` -> `leveldb.doCompaction`. Looking at `doCompaction` right now, though, and not seeing where it might be calling the callback twice...

**Comment by nolanlawson** [comment]
Ah, I see the bug now. Fixing.

**Comment by marten-de-vries** [comment]
Probably solved with at least the compact() change.
