### ISSUE TITLE
2.1.1 - bluebird warnings -Warning: a promise was created in a handler...

### ISSUE THREAD

**Issue by itsjimbo** [pouchdb/express-pouchdb#408]
Plenty of these warnings, wondering if they are from the bluebird version, code is similar to examples, just wondering if anyone else is getting these

```
(node:6390) Warning: a promise was created in a handler at ../app/node_modules/express-pouchdb/lib/daemon-manager.js:26:16 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (../app/node_modules/bluebird/js/release/promise.js:195:13)
```

**Comment by nolanlawson** [comment]
Thanks for reporting!

**Comment by nolanlawson** [comment]
fixed in https://github.com/pouchdb/express-pouchdb/pull/411
